require('dotenv').config();
const mailer = require('./lib/mailer');

async function run() {
  try {
    const info = await mailer.sendMail({
      from: process.env.EMAIL_USER,
      to: process.env.EMAIL_USER,
      subject: 'Test SMTP from local script',
      text: 'This is a test message generated by test_send.js',
    });
    console.log('Send success:', info);
    process.exit(0);
  } catch (err) {
    console.error('Send failed:', err && err.stack ? err.stack : err);
    process.exit(1);
  }
}

run();
